<?php
/**
 * UserAuthenticationMethod
 *
 * PHP version 5
 *
 * @category Class
 * @package  AgendarEntrega\Pedido
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AgendarEntrega\Pedido\Model;
use \AgendarEntrega\Pedido\ObjectSerializer;

/**
 * UserAuthenticationMethod Class Doc Comment
 *
 * @category Class
 * @package  AgendarEntrega\Pedido
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserAuthenticationMethod
{
    /**
     * Possible values of this enum
     */
    const NONE = 'AuthenticationMethod_NONE';
    const USERNAME = 'AuthenticationMethod_USERNAME';
    const EMAIL = 'AuthenticationMethod_EMAIL';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::USERNAME,
            self::EMAIL,
        ];
    }
}


