<?php
/**
 * PedidoServiceApi
 * PHP version 5
 *
 * @category Class
 * @package  AgendarEntrega\Pedido
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * gitlab.com/agendarentrega/servicos/pedido/proto/config.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AgendarEntrega\Pedido\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use AgendarEntrega\Pedido\ApiException;
use AgendarEntrega\Pedido\Configuration;
use AgendarEntrega\Pedido\HeaderSelector;
use AgendarEntrega\Pedido\ObjectSerializer;

/**
 * PedidoServiceApi Class Doc Comment
 *
 * @category Class
 * @package  AgendarEntrega\Pedido
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PedidoServiceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation alterarStatusPedido
     *
     * @param  string $cnpjEmitente cnpjEmitente (required)
     * @param  string $codigo codigo (required)
     * @param  \AgendarEntrega\Pedido\Model\PedidoAlterarStatusPedidoRequest $body body (required)
     *
     * @throws \AgendarEntrega\Pedido\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \AgendarEntrega\Pedido\Model\PedidoAlterarStatusPedidoResponse
     */
    public function alterarStatusPedido($cnpjEmitente, $codigo, $body)
    {
        list($response) = $this->alterarStatusPedidoWithHttpInfo($cnpjEmitente, $codigo, $body);
        return $response;
    }

    /**
     * Operation alterarStatusPedidoWithHttpInfo
     *
     * @param  string $cnpjEmitente (required)
     * @param  string $codigo (required)
     * @param  \AgendarEntrega\Pedido\Model\PedidoAlterarStatusPedidoRequest $body (required)
     *
     * @throws \AgendarEntrega\Pedido\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \AgendarEntrega\Pedido\Model\PedidoAlterarStatusPedidoResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function alterarStatusPedidoWithHttpInfo($cnpjEmitente, $codigo, $body)
    {
        $returnType = '\AgendarEntrega\Pedido\Model\PedidoAlterarStatusPedidoResponse';
        $request = $this->alterarStatusPedidoRequest($cnpjEmitente, $codigo, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AgendarEntrega\Pedido\Model\PedidoAlterarStatusPedidoResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation alterarStatusPedidoAsync
     *
     * 
     *
     * @param  string $cnpjEmitente (required)
     * @param  string $codigo (required)
     * @param  \AgendarEntrega\Pedido\Model\PedidoAlterarStatusPedidoRequest $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function alterarStatusPedidoAsync($cnpjEmitente, $codigo, $body)
    {
        return $this->alterarStatusPedidoAsyncWithHttpInfo($cnpjEmitente, $codigo, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation alterarStatusPedidoAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $cnpjEmitente (required)
     * @param  string $codigo (required)
     * @param  \AgendarEntrega\Pedido\Model\PedidoAlterarStatusPedidoRequest $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function alterarStatusPedidoAsyncWithHttpInfo($cnpjEmitente, $codigo, $body)
    {
        $returnType = '\AgendarEntrega\Pedido\Model\PedidoAlterarStatusPedidoResponse';
        $request = $this->alterarStatusPedidoRequest($cnpjEmitente, $codigo, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'alterarStatusPedido'
     *
     * @param  string $cnpjEmitente (required)
     * @param  string $codigo (required)
     * @param  \AgendarEntrega\Pedido\Model\PedidoAlterarStatusPedidoRequest $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function alterarStatusPedidoRequest($cnpjEmitente, $codigo, $body)
    {
        // verify the required parameter 'cnpjEmitente' is set
        if ($cnpjEmitente === null || (is_array($cnpjEmitente) && count($cnpjEmitente) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $cnpjEmitente when calling alterarStatusPedido'
            );
        }
        // verify the required parameter 'codigo' is set
        if ($codigo === null || (is_array($codigo) && count($codigo) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $codigo when calling alterarStatusPedido'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling alterarStatusPedido'
            );
        }

        $resourcePath = '/pedidos/importados/by-emitente/{cnpjEmitente}/{codigo}/set-status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($cnpjEmitente !== null) {
            $resourcePath = str_replace(
                '{' . 'cnpjEmitente' . '}',
                ObjectSerializer::toPathValue($cnpjEmitente),
                $resourcePath
            );
        }
        // path params
        if ($codigo !== null) {
            $resourcePath = str_replace(
                '{' . 'codigo' . '}',
                ObjectSerializer::toPathValue($codigo),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation importarPedido
     *
     * @param  \AgendarEntrega\Pedido\Model\PedidoImportarPedidoRequest $body body (required)
     *
     * @throws \AgendarEntrega\Pedido\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \AgendarEntrega\Pedido\Model\PedidoImportarPedidoResponse
     */
    public function importarPedido($body)
    {
        list($response) = $this->importarPedidoWithHttpInfo($body);
        return $response;
    }

    /**
     * Operation importarPedidoWithHttpInfo
     *
     * @param  \AgendarEntrega\Pedido\Model\PedidoImportarPedidoRequest $body (required)
     *
     * @throws \AgendarEntrega\Pedido\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \AgendarEntrega\Pedido\Model\PedidoImportarPedidoResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function importarPedidoWithHttpInfo($body)
    {
        $returnType = '\AgendarEntrega\Pedido\Model\PedidoImportarPedidoResponse';
        $request = $this->importarPedidoRequest($body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\AgendarEntrega\Pedido\Model\PedidoImportarPedidoResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation importarPedidoAsync
     *
     * 
     *
     * @param  \AgendarEntrega\Pedido\Model\PedidoImportarPedidoRequest $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function importarPedidoAsync($body)
    {
        return $this->importarPedidoAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation importarPedidoAsyncWithHttpInfo
     *
     * 
     *
     * @param  \AgendarEntrega\Pedido\Model\PedidoImportarPedidoRequest $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function importarPedidoAsyncWithHttpInfo($body)
    {
        $returnType = '\AgendarEntrega\Pedido\Model\PedidoImportarPedidoResponse';
        $request = $this->importarPedidoRequest($body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'importarPedido'
     *
     * @param  \AgendarEntrega\Pedido\Model\PedidoImportarPedidoRequest $body (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function importarPedidoRequest($body)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling importarPedido'
            );
        }

        $resourcePath = '/pedidos/importar';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
